// ─────────────────────────────────────────────────────────────────────────────
// Timeline → .ics
//
// The Milestones tab knows every dated thing in a student's application year —
// their own deadlines, their college list's EA/ED/RD dates, the test sittings
// they are on track for. That knowledge was previously trapped inside the app,
// which is exactly the wrong place for it: the calendar a 17-year-old actually
// checks is the one on their phone.
//
// This writes a standards-compliant iCalendar file (RFC 5545) with no
// dependency — jspdf is already 300kB and a calendar file is 40 lines of string
// building. All-day VEVENTs, because every milestone here is a date, not a
// time, and a timed event would force us to invent an hour we do not know.
//
// Generated dates are marked in the description rather than silently exported
// as fact: the same honesty rule the UI follows (see `confidence` in
// src/lib/timeline.js) has to survive the trip into Google Calendar, because
// once it is out of our app nobody can add the caveat later.
// ─────────────────────────────────────────────────────────────────────────────

const PRODID = '-//MedSchoolPrep//Milestones//EN';

/** `2026-11-01` → `20261101`, the DATE value type iCalendar wants. */
const toIcsDate = (day) => String(day || '').replace(/-/g, '');

/** The day after `day`, since an all-day VEVENT's DTEND is exclusive. */
function nextDay(day) {
  const d = new Date(`${day}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + 1);
  return d.toISOString().slice(0, 10).replace(/-/g, '');
}

function stamp(now = new Date()) {
  return `${now.toISOString().replace(/[-:]/g, '').split('.')[0]}Z`;
}

/**
 * Escapes a value for a TEXT-typed property. Order matters: backslashes first,
 * or we would escape the escapes we just added.
 */
function esc(text) {
  return String(text ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\r?\n/g, '\\n');
}

/**
 * Folds a content line to 75 octets, continuing with a leading space, per
 * RFC 5545 §3.1. Measured in UTF-8 bytes rather than characters — a line of
 * em-dashes is well under 75 characters and well over 75 octets, and some
 * parsers really do reject it.
 */
function fold(line) {
  const bytes = new TextEncoder().encode(line);
  if (bytes.length <= 75) return line;
  const out = [];
  let chunk = '';
  let size = 0;
  const limit = () => (out.length === 0 ? 75 : 74); // continuations spend one octet on the leading space
  for (const ch of line) {
    const n = new TextEncoder().encode(ch).length;
    if (size + n > limit()) { out.push(chunk); chunk = ''; size = 0; }
    chunk += ch;
    size += n;
  }
  if (chunk) out.push(chunk);
  return out.map((c, i) => (i === 0 ? c : ` ${c}`)).join('\r\n');
}

/**
 * Milestone events → an iCalendar document.
 *
 * @param {Array} events   timeline events ({ id, date, title, detail, why, kind, confidence, source })
 * @param {object} [opts]
 * @param {string} [opts.calendarName]  X-WR-CALNAME, what Apple/Google label the import
 * @param {Date}   [opts.now]           injectable clock (DTSTAMP), so this is testable
 * @returns {string} the file's contents, CRLF-delimited
 */
export function buildIcs(events = [], { calendarName = 'MedSchoolPrep Milestones', now = new Date() } = {}) {
  const dtstamp = stamp(now);
  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    `PRODID:${PRODID}`,
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${esc(calendarName)}`,
  ];

  events.filter((e) => e && e.date).forEach((e) => {
    const generated = e.confidence === 'typical';
    const body = [
      e.detail,
      e.why,
      generated
        ? 'Typical-year date generated by MedSchoolPrep from your class year — confirm it on the official site before you plan around it.'
        : 'From a date you entered in MedSchoolPrep.',
    ].filter(Boolean).join('\n\n');

    lines.push(
      'BEGIN:VEVENT',
      `UID:${esc(e.id)}@medschoolprep`,
      `DTSTAMP:${dtstamp}`,
      `DTSTART;VALUE=DATE:${toIcsDate(e.date)}`,
      `DTEND;VALUE=DATE:${nextDay(e.date)}`,
      `SUMMARY:${esc(generated ? `${e.title} (typical)` : e.title)}`,
      `DESCRIPTION:${esc(body)}`,
      `CATEGORIES:${esc(e.kind || 'milestone')}`,
      'TRANSP:TRANSPARENT',
      // A generated date is a best guess, so it is exported as tentative — every
      // major calendar renders that differently from a confirmed commitment.
      `STATUS:${generated ? 'TENTATIVE' : 'CONFIRMED'}`,
      'BEGIN:VALARM',
      'TRIGGER:-P2D',
      'ACTION:DISPLAY',
      `DESCRIPTION:${esc(`${e.title} — 2 days out`)}`,
      'END:VALARM',
      'END:VEVENT',
    );
  });

  lines.push('END:VCALENDAR');
  return lines.map(fold).join('\r\n');
}

/**
 * Builds the file and hands it to the browser. Returns how many events went in
 * so the caller can say something truthful in its toast.
 */
export function downloadIcs(events, opts = {}) {
  const ics = buildIcs(events, opts);
  const blob = new Blob([ics], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = opts.filename || 'medschoolprep-milestones.ics';
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Revoked on the next tick rather than immediately: Safari has historically
  // canceled the download if the object URL dies inside the same task.
  setTimeout(() => URL.revokeObjectURL(url), 0);
  return events.filter((e) => e && e.date).length;
}
