// ─────────────────────────────────────────────────────────────────────────────
// The document a senior needs in October and cannot reconstruct from memory.
//
// ── What this is ────────────────────────────────────────────────────────────
// Four years of logging, turned into one formatted record: profile, every
// activity grouped by category with totals and date ranges, the shadowing log
// with specialties and supervisors and dates, certifications, awards,
// competitions, leadership, coursework, the recommender list, and a
// chronological four-year timeline.
//
// A student who has been logging since ninth grade is holding something no
// amount of remembering can reproduce — nobody recalls which Saturday in March
// of tenth grade they were at the free clinic, or that the total came to 214
// hours across eleven sites. The logs know. This turns them into the thing they
// were always for.
//
// ── The two modes, and why the second one is dangerous ──────────────────────
//   'application' — clean, transcribable, nothing in it a student would not
//                   hand to an admissions reader. This is the one they print in
//                   October with the Common App open beside it.
//   'archive'     — the same record PLUS their private reflections: the journal
//                   entries and the "why this pathway" working document.
//
// The archive mode is genuinely sensitive. The reflection journal is the one
// part of the whole Portfolio a fifteen-year-old writes honestly in, and it is
// honest precisely because nothing else can see it — not a parent, not a
// counselor, not a scoring engine (see the header of ReflectionJournal.jsx). A
// single leak of that content into a parent-visible surface would not just
// breach a boundary, it would end the honesty that makes the journal worth
// anything, permanently and invisibly.
//
// So `buildDossier` REFUSES rather than degrades: called with mode 'archive'
// and any audience other than 'student', it throws. It does not quietly strip
// the reflections and return a document, because a function that silently
// downgrades is a function whose caller stops checking. `assertStudentOnly` is
// exported so UI can gate the button on the same rule that guards the data.
//
// ── Purity ──────────────────────────────────────────────────────────────────
// Pure. Rows in, a plain document object out, with `now` injectable so the
// verify script can assert grade bucketing and date ranges at fixed dates. The
// renderer (src/lib/exportPDF.js) knows nothing about the schema and this
// module knows nothing about jsPDF.
// ─────────────────────────────────────────────────────────────────────────────

export const DOSSIER_MODES = {
  application: {
    id: 'application',
    label: 'Application-ready',
    blurb: 'Clean and transcribable. Everything an admissions reader would see, nothing they would not. This is the one you print with the Common App open beside it.',
    includesReflections: false,
    audiences: ['student', 'parent', 'counselor'],
  },
  archive: {
    id: 'archive',
    label: 'Personal archive',
    blurb: 'Everything above plus your reflection journal and your "why this pathway" working document. Yours only — this version is never visible to a parent or counselor account, and cannot be generated by one.',
    includesReflections: true,
    audiences: ['student'],
  },
};

/**
 * The categories activities are grouped under, in the order a reader expects.
 *
 * Grouping matters more than it looks: eleven ungrouped activity lines read as
 * a list of things that happened, and the same eleven grouped with hour totals
 * read as four sustained commitments — which is what they actually are, and
 * what the reader is trying to work out.
 */
export const ACTIVITY_GROUPS = [
  { id: 'clinical', label: 'Clinical & Patient Care', match: /clinic|patient|hospital|medical|health|shadow|scrib|cna|emt/i },
  { id: 'research', label: 'Research & Academic', match: /research|lab|science|academic|study|olympiad/i },
  { id: 'service', label: 'Community Service & Volunteering', match: /volunteer|service|community|charity|outreach|tutor/i },
  { id: 'leadership', label: 'Leadership & Organizations', match: /leader|president|captain|founder|club|council|officer|hosa|organization/i },
  { id: 'work', label: 'Work & Employment', match: /work|job|employ|intern|paid/i },
  { id: 'arts-athletics', label: 'Arts & Athletics', match: /art|music|theat|danc|sport|athlet|team|band|orchestra/i },
  { id: 'other', label: 'Other Activities', match: null },
];

const num = (v) => (Number.isFinite(Number(v)) ? Number(v) : 0);
const str = (v) => (v == null ? '' : String(v).trim());
const nonEmpty = (v) => str(v).length > 0;

/** 'YYYY-MM-DD' → a Date at local midnight, or null. */
function day(value) {
  if (!value) return null;
  const d = new Date(`${String(value).slice(0, 10)}T00:00:00`);
  return Number.isNaN(d.getTime()) ? null : d;
}

const fmtDay = (v) => {
  const d = day(v);
  return d ? d.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }) : null;
};
const fmtMonth = (v) => {
  const d = day(v);
  return d ? d.toLocaleDateString(undefined, { month: 'short', year: 'numeric' }) : null;
};

/** "Mar 2024 – Nov 2025", or a single month when there is only one date. */
export function dateRangeLabel(dates = []) {
  const sorted = dates.filter(Boolean).map(String).sort();
  if (!sorted.length) return null;
  const first = fmtMonth(sorted[0]);
  const last = fmtMonth(sorted[sorted.length - 1]);
  return first === last ? first : `${first} – ${last}`;
}

/** Which of ACTIVITY_GROUPS an activity row belongs to. */
export function groupForActivity(activity) {
  const hay = [activity?.activity_type, activity?.position, activity?.organization].map(str).join(' ');
  for (const g of ACTIVITY_GROUPS) {
    if (g.match && g.match.test(hay)) return g.id;
  }
  return 'other';
}

/** Estimated total hours for an activity, from hours/week × weeks/year. */
export function activityHours(activity) {
  const perWeek = num(activity?.hours_per_week);
  const weeks = num(activity?.weeks_per_year);
  if (perWeek && weeks) return Math.round(perWeek * weeks);
  return 0;
}

/**
 * The school year a date falls in, expressed as a grade if we know when they
 * started. Used for the timeline's year headings.
 *
 * A US school year straddles the calendar year, so anything from August onward
 * belongs to the year that is starting. Getting this wrong puts a September
 * shift in the wrong grade, which is exactly the sort of quiet error that makes
 * a student distrust the whole document.
 */
export function schoolYearOf(dateValue) {
  const d = day(dateValue);
  if (!d) return null;
  const y = d.getFullYear();
  return d.getMonth() >= 7 ? y : y - 1;   // month 7 = August
}

export function schoolYearLabel(startYear) {
  return startYear == null ? 'Undated' : `${startYear}–${String(startYear + 1).slice(2)}`;
}

/**
 * Refuses an archive-mode build for anyone but the student.
 *
 * Exported so the UI gates the button with exactly the same predicate the data
 * layer enforces, rather than with a second, drifting copy of the rule.
 */
export function assertStudentOnly(mode, audience) {
  const spec = DOSSIER_MODES[mode];
  if (!spec) throw new Error(`Unknown export mode: ${mode}`);
  if (!audience) {
    throw new Error('buildDossier requires an explicit audience — "student", "parent" or "counselor".');
  }
  if (!spec.audiences.includes(audience)) {
    throw new Error(
      `The ${spec.label} export can only be generated by the student's own account, because it contains their private reflections (got audience "${audience}").`,
    );
  }
  return true;
}

/**
 * Builds the whole document model.
 *
 * @param {object} input
 *   mode        'application' | 'archive'
 *   audience    'student' | 'parent' | 'counselor'  (archive requires 'student')
 *   student     { name, gradeLabel, pathwayLabel, schoolName }
 *   snapshot    the Portfolio snapshot (see src/lib/portfolioData.js)
 *   reflections reflection_entries rows — only read in archive mode
 *   now         epoch ms, injectable for tests
 *
 * @returns a plain document: { meta, sections: [...], stats }
 *   Every section is { id, title, kind, rows|groups|entries, note? } so the
 *   renderer can walk it without knowing what any of it means.
 */
export function buildDossier({
  mode = 'application',
  // No default. `audience` gates the private-reflections export, and a
  // permissive default is how a privacy gate stops being one: a caller that
  // forgets the argument would silently be treated as the student. Omitting it
  // throws, which is a bug the first caller hits rather than a leak nobody sees.
  audience = null,
  student = {},
  snapshot = {},
  reflections = [],
  now = Date.now(),
} = {}) {
  assertStudentOnly(mode, audience);
  const spec = DOSSIER_MODES[mode];

  const activities = snapshot.activities || [];
  const awards = snapshot.awards || [];
  const clinical = snapshot.clinicalHours || [];
  const research = snapshot.research || [];
  const certs = snapshot.skills || [];
  const gpa = snapshot.gpaEntries || [];
  const recommenders = snapshot.recommenders || [];
  const tests = snapshot.testScores || [];
  const essays = snapshot.essays || [];

  const sections = [];

  // ── Activities, grouped, with totals and date ranges ────────────────────
  const groups = ACTIVITY_GROUPS.map(g => {
    const rows = activities.filter(a => groupForActivity(a) === g.id);
    if (!rows.length) return null;
    const hours = rows.reduce((s, a) => s + activityHours(a), 0);
    const grades = [...new Set(rows.flatMap(a => a.grade_levels || []))].sort();
    return {
      id: g.id,
      label: g.label,
      totalHours: hours,
      count: rows.length,
      gradeSpan: grades.length ? `Grades ${grades[0]}–${grades[grades.length - 1]}` : null,
      rows: rows.map(a => ({
        title: [str(a.position), str(a.organization)].filter(Boolean).join(' — ') || 'Activity',
        meta: [
          str(a.activity_type),
          a.leadership_role ? 'Leadership role' : null,
          (a.grade_levels || []).length ? `Grades ${(a.grade_levels || []).join(', ')}` : null,
          num(a.hours_per_week) ? `${num(a.hours_per_week)} hrs/week` : null,
          num(a.weeks_per_year) ? `${num(a.weeks_per_year)} weeks/year` : null,
          activityHours(a) ? `≈${activityHours(a)} hrs total` : null,
          str(a.status),
        ].filter(Boolean).join(' · '),
        description: str(a.description),
        impact: str(a.impact),
        verified: a.verification_status === 'verified',
      })),
    };
  }).filter(Boolean);

  if (groups.length) {
    sections.push({
      id: 'activities',
      title: 'Activities & Hours',
      kind: 'grouped',
      groups,
      note: 'Hour totals are estimates from the hours-per-week and weeks-per-year you recorded, not a separate count.',
    });
  }

  // ── The shadowing / clinical log ────────────────────────────────────────
  if (clinical.length) {
    const bySite = {};
    clinical.forEach(e => {
      const key = str(e.site_name) || 'Unrecorded site';
      (bySite[key] ||= []).push(e);
    });
    sections.push({
      id: 'clinical',
      title: 'Shadowing, Clinical & Volunteer Hours',
      kind: 'grouped',
      note: 'Every entry was logged with its own date at the time it happened. Nothing here was reconstructed afterwards.',
      groups: Object.entries(bySite).map(([site, rows]) => ({
        id: site,
        label: site,
        totalHours: rows.reduce((s, e) => s + num(e.hours), 0),
        count: rows.length,
        gradeSpan: dateRangeLabel(rows.map(e => e.entry_date)),
        rows: rows
          .slice()
          .sort((a, b) => String(a.entry_date).localeCompare(String(b.entry_date)))
          .map(e => ({
            title: `${fmtDay(e.entry_date) || 'Undated'} — ${num(e.hours)} hrs`,
            meta: [
              str(e.site_type),
              str(e.experience_kind),
              nonEmpty(e.supervisor_name) ? `Supervisor: ${str(e.supervisor_name)}` : null,
              e.verification_status === 'verified' ? 'Verified' : 'Self-reported',
            ].filter(Boolean).join(' · '),
            description: str(e.notes),
            verified: e.verification_status === 'verified',
          })),
      })).sort((a, b) => b.totalHours - a.totalHours),
    });
  }

  // ── Research ────────────────────────────────────────────────────────────
  if (research.length) {
    sections.push({
      id: 'research',
      title: 'Research Experience',
      kind: 'rows',
      rows: research.map(r => ({
        title: [str(r.title), str(r.institution)].filter(Boolean).join(' — ') || 'Project',
        meta: [
          str(r.status),
          nonEmpty(r.mentor_name) ? `Mentor: ${str(r.mentor_name)}` : null,
          num(r.hours) ? `${num(r.hours)} hrs` : null,
          nonEmpty(r.publication_url) ? 'Publication or poster linked' : null,
        ].filter(Boolean).join(' · '),
        description: str(r.description),
      })),
    });
  }

  // ── Awards, competitions and leadership ─────────────────────────────────
  if (awards.length) {
    sections.push({
      id: 'awards',
      title: 'Awards, Competitions & Leadership',
      kind: 'rows',
      rows: awards.map(a => ({
        title: str(a.title) || 'Award',
        meta: [
          str(a.level),
          a.grade_level ? `Grade ${a.grade_level}` : null,
          str(a.issuing_organization),
          str(a.category),
        ].filter(Boolean).join(' · ') || 'No level recorded',
        verified: a.verification_status === 'verified',
      })),
    });
  }

  // ── Certifications ──────────────────────────────────────────────────────
  if (certs.length) {
    const today = new Date(now).toISOString().slice(0, 10);
    sections.push({
      id: 'certifications',
      title: 'Certifications & Credentials',
      kind: 'rows',
      note: 'An expired credential is shown as expired rather than quietly dropped — the reader can see the history, and you can see what to renew.',
      rows: certs.map(c => {
        const expired = nonEmpty(c.expiry_date) && String(c.expiry_date) < today;
        return {
          title: str(c.name) || 'Certification',
          meta: [
            str(c.issuing_body),
            c.earned_date ? `Earned ${fmtDay(c.earned_date)}` : null,
            c.expiry_date ? `${expired ? 'EXPIRED' : 'Valid to'} ${fmtDay(c.expiry_date)}` : null,
            str(c.state_code),
          ].filter(Boolean).join(' · ') || 'No issuing body recorded',
          flag: expired ? 'expired' : null,
        };
      }),
    });
  }

  // ── Coursework and grades ───────────────────────────────────────────────
  if (gpa.length || tests.length) {
    const sortedGpa = gpa.slice().sort((a, b) => String(a.term).localeCompare(String(b.term)));
    sections.push({
      id: 'coursework',
      title: 'Coursework & Academic Record',
      kind: 'rows',
      rows: [
        ...sortedGpa.map(g => ({
          title: str(g.term) || 'Term',
          meta: [
            `GPA ${g.gpa}`,
            g.weighted ? 'weighted' : 'unweighted',
            str(g.course_rigor),
          ].filter(Boolean).join(' · '),
        })),
        ...tests.map(t => ({
          title: `${str(t.test_type) || 'Test'}${t.is_target ? ' (target)' : ''}`,
          meta: [
            t.composite != null ? `Composite ${t.composite}` : null,
            t.test_date ? fmtDay(t.test_date) : null,
            t.section_scores && typeof t.section_scores === 'object'
              ? Object.entries(t.section_scores).map(([k, v]) => `${k} ${v}`).join(', ')
              : null,
          ].filter(Boolean).join(' · '),
        })),
      ],
    });
  }

  // ── Recommenders ────────────────────────────────────────────────────────
  if (recommenders.length) {
    sections.push({
      id: 'recommenders',
      title: 'Letters of Recommendation',
      kind: 'rows',
      note: 'Contact details are deliberately not included. This is a list of who is writing and where each letter stands, not a directory to hand to anyone.',
      rows: recommenders.map(r => ({
        title: str(r.name) || 'Recommender',
        meta: [
          str(r.relationship),
          r.type === 'committee' ? 'Committee letter' : 'Individual letter',
          str(r.status),
          r.due_date ? `Due ${fmtDay(r.due_date)}` : null,
          r.asked_at ? `Asked ${fmtDay(r.asked_at)}` : null,
        ].filter(Boolean).join(' · '),
      })),
    });
  }

  // ── The four-year timeline ──────────────────────────────────────────────
  const timelineEvents = [
    ...clinical.map(e => ({
      date: e.entry_date,
      label: `${num(e.hours)} hrs — ${str(e.site_name) || 'clinical'}`,
      detail: [str(e.experience_kind), str(e.supervisor_name)].filter(Boolean).join(' · '),
      kind: 'clinical',
    })),
    ...certs.filter(c => nonEmpty(c.earned_date)).map(c => ({
      date: c.earned_date,
      label: `Earned ${str(c.name)}`,
      detail: str(c.issuing_body),
      kind: 'certification',
    })),
    ...gpa.filter(g => nonEmpty(g.term)).map(g => ({
      date: null,
      term: str(g.term),
      label: `${str(g.term)} — GPA ${g.gpa}`,
      detail: g.weighted ? 'weighted' : 'unweighted',
      kind: 'academic',
    })),
    ...tests.filter(t => nonEmpty(t.test_date)).map(t => ({
      date: t.test_date,
      label: `${str(t.test_type)} ${t.composite ?? ''}`.trim(),
      detail: 'Test sitting',
      kind: 'test',
    })),
    ...recommenders.filter(r => nonEmpty(r.asked_at)).map(r => ({
      date: r.asked_at,
      label: `Asked ${str(r.name)} for a letter`,
      detail: str(r.relationship),
      kind: 'recommender',
    })),
  ].filter(e => e.date || e.term);

  if (timelineEvents.length) {
    const byYear = {};
    timelineEvents.forEach(e => {
      const y = e.date ? schoolYearOf(e.date) : null;
      (byYear[y == null ? 'undated' : y] ||= []).push(e);
    });
    const years = Object.keys(byYear)
      .sort((a, b) => (a === 'undated' ? 1 : b === 'undated' ? -1 : Number(a) - Number(b)));
    sections.push({
      id: 'timeline',
      title: 'Four-Year Timeline',
      kind: 'timeline',
      note: 'Built from the dates you recorded as things happened. This is the part nobody can reconstruct from memory in October, and it is the reason four years of logging was worth it.',
      years: years.map(y => ({
        label: y === 'undated' ? 'Undated' : schoolYearLabel(Number(y)),
        events: byYear[y]
          .slice()
          .sort((a, b) => String(a.date || a.term).localeCompare(String(b.date || b.term)))
          .map(e => ({ ...e, dateLabel: e.date ? fmtDay(e.date) : e.term })),
      })),
    });
  }

  // ── Private reflections — archive mode only ─────────────────────────────
  if (spec.includesReflections) {
    const journal = (reflections || [])
      .slice()
      .sort((a, b) => String(a.entry_date).localeCompare(String(b.entry_date)));
    const workingDoc = essays.filter(e => e.essay_kind === 'why_pathway');

    // Deliberately NOT included here: an activity's `impact` field. It reads
    // like a private note and is not one — it is the "what changed because you
    // were there" line of a Common App activity entry, written to be read by an
    // admissions officer. Treating it as private would strip application
    // content out of the application-ready document, which is the opposite
    // error to the one this section is careful about, and just as wrong.
    if (journal.length || workingDoc.length) {
      sections.push({
        id: 'reflections',
        title: 'Your Reflections — Private',
        kind: 'longform',
        note: 'This section exists only in your personal archive. It is never included in the application-ready export, and a parent or counselor account cannot generate this document at all.',
        entries: [
          ...workingDoc.map(e => ({
            heading: str(e.title) || 'Why this pathway — working document',
            dateLabel: null,
            body: str(e.content),
          })),
          ...journal.map(r => ({
            heading: str(r.prompt_text) || 'Journal entry',
            dateLabel: fmtDay(r.entry_date),
            body: str(r.content),
          })),
        ].filter(e => nonEmpty(e.body)),
      });
    }
  }

  const clinicalTotal = clinical.reduce((s, e) => s + num(e.hours), 0);
  const activityTotal = activities.reduce((s, a) => s + activityHours(a), 0);
  const researchTotal = research.reduce((s, r) => s + num(r.hours), 0);
  const allDates = [
    ...clinical.map(e => e.entry_date),
    ...certs.map(c => c.earned_date),
    ...tests.map(t => t.test_date),
  ].filter(Boolean);

  return {
    meta: {
      mode: spec.id,
      modeLabel: spec.label,
      audience,
      studentName: str(student.name) || null,
      gradeLabel: str(student.gradeLabel) || null,
      pathwayLabel: str(student.pathwayLabel) || null,
      schoolName: str(student.schoolName) || null,
      generatedAt: new Date(now).toISOString(),
      generatedLabel: new Date(now).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }),
      recordSpan: dateRangeLabel(allDates),
      containsPrivate: spec.includesReflections,
    },
    sections,
    stats: {
      activities: activities.length,
      awards: awards.length,
      clinicalEntries: clinical.length,
      clinicalHours: clinicalTotal,
      activityHours: activityTotal,
      researchHours: researchTotal,
      totalHours: clinicalTotal + activityTotal + researchTotal,
      certifications: certs.length,
      research: research.length,
      recommenders: recommenders.length,
      terms: gpa.length,
      sites: [...new Set(clinical.map(e => str(e.site_name)).filter(Boolean))].length,
      supervisors: [...new Set(clinical.map(e => str(e.supervisor_name)).filter(Boolean))].length,
      specialties: [...new Set(clinical.map(e => str(e.site_type)).filter(Boolean))].length,
      sectionCount: sections.length,
    },
  };
}

/**
 * True when there is enough on record for the document to be worth generating.
 *
 * A dossier with nothing in it is not a teaser, it is a disappointment, and
 * showing a locked "unlock the full version" screen over an empty record is the
 * worst version of a paywall. Below this, the UI says "log some things first"
 * rather than "pay".
 */
export function hasEnoughForDossier(snapshot = {}) {
  const counts = [
    (snapshot.activities || []).length,
    (snapshot.clinicalHours || []).length,
    (snapshot.awards || []).length,
    (snapshot.skills || []).length,
    (snapshot.research || []).length,
    (snapshot.gpaEntries || []).length,
  ];
  return counts.reduce((s, n) => s + n, 0) >= 3;
}
