#!/usr/bin/env node
/**
 * Generates public/sitemap.xml AND public/robots.txt from the shared route table
 * in src/lib/seoRoutes.js, at build time (`npm run build` runs `npm run sitemap`
 * first).
 *
 * Why a generator instead of two hand-written files: they have to agree with
 * each other, with the app's real routes, with the canonical URL each page
 * serves, and with the noindex logic in src/lib/seo.js — and hand-edited copies
 * drift. They used to drift in exactly the way that matters: the sitemap listed
 * seven URLs and all seven served `<link rel="canonical" href="…/">`, so six of
 * them were, as far as any crawler could tell, duplicates of the seventh.
 *
 * So the route facts moved to src/lib/seoRoutes.js, which is now the single
 * source for all four consumers:
 *
 *   • this file            → sitemap.xml + robots.txt
 *   • scripts/prerenderSeo → the static HTML each URL is served, canonical
 *                            included
 *   • src/lib/seo.js       → the client-side canonical/robots for JS crawlers
 *   • scripts/verifySeo    → the build guard that fails if the above disagree
 *
 * `lastmod` — the one sitemap field worth getting right, since Google uses it to
 * decide whether a re-crawl is worth its time — is computed here, from the
 * newest git commit touching the files that actually render each route.
 *
 * ── Which URLs belong in the table ────────────────────────────────────────────
 *
 * See the header of src/lib/seoRoutes.js. Short version: only URLs where a
 * signed-out visitor reaches a distinct page. The app's client-side routes
 * (/sat/practice, /portfolio/essays, …) all render the landing page to a visitor
 * with no session, so listing them would hand Google a dozen URLs resolving to
 * the same page. They are Disallow-ed below and noindexed client-side instead.
 */

import { execFileSync } from 'node:child_process';
import { writeFileSync, existsSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { PUBLIC_ROUTES, DISALLOW, AI_CRAWLERS, ORIGIN, absoluteUrl } from '../src/lib/seoRoutes.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

/** Newest commit date across `files`, as YYYY-MM-DD. Null if git can't say. */
function gitLastModified(files) {
  const present = files.filter((f) => existsSync(path.join(ROOT, f)));
  if (!present.length) return null;
  let newest = null;
  for (const file of present) {
    try {
      const out = execFileSync(
        'git',
        ['log', '-1', '--format=%cs', '--', file],
        { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] },
      ).trim();
      if (out && (!newest || out > newest)) newest = out;
    } catch {
      // Shallow clone, no git in the image, or a file with no history yet —
      // fall through to the mtime fallback below.
    }
  }
  if (newest) return newest;
  // No git history available: mtime is a weaker but still truthful signal.
  const newestMtime = Math.max(
    ...present.map((f) => statSync(path.join(ROOT, f)).mtimeMs),
  );
  return new Date(newestMtime).toISOString().slice(0, 10);
}

function xmlEscape(s) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function buildSitemap(routes) {
  const entries = routes.map((route) => {
    if (!route.path.startsWith('/')) {
      throw new Error(`Route path must start with '/': ${route.path}`);
    }
    const lastmod = gitLastModified(route.sources);
    const lines = [
      `    <loc>${xmlEscape(absoluteUrl(route.path))}</loc>`,
      lastmod ? `    <lastmod>${lastmod}</lastmod>` : null,
      `    <changefreq>${route.changefreq}</changefreq>`,
      `    <priority>${route.priority}</priority>`,
    ].filter(Boolean);
    return `  <url>\n${lines.join('\n')}\n  </url>`;
  });

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
    '        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9',
    '                            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">',
    ...entries,
    '</urlset>',
    '',
  ].join('\n');
}

function buildRobots(routes) {
  return [
    '# MedSchoolPrep — ' + ORIGIN,
    '#',
    '# Generated by scripts/generateSitemap.mjs from src/lib/seoRoutes.js —',
    '# edit the route table there, not this file.',
    '#',
    '# The crawlable surface is the landing page, the two account screens, the',
    '# parent pages and the two legal documents. Each of those is served its own',
    '# prerendered HTML with its own canonical (scripts/prerenderSeo.mjs).',
    '#',
    '# Everything Disallow-ed below is either an API path or a signed-in app',
    '# route: it renders the landing page to a crawler because there is no',
    '# session, so indexing it would just create duplicates of the URL we',
    '# actually want ranked.',
    '#',
    '# The AI-crawler blocks below repeat the same Allow/Disallow rules under',
    '# their own user-agent so it is unambiguous that they are welcome — see',
    '# AI_CRAWLERS in src/lib/seoRoutes.js.',
    '',
    ...['*', ...AI_CRAWLERS].flatMap((agent) => [
      `User-agent: ${agent}`,
      'Allow: /$',
      ...routes.filter((r) => r.path !== '/').map((r) => `Allow: ${r.path}`),
      ...DISALLOW.map((prefix) => `Disallow: ${prefix}`),
      '',
    ]),
    `Sitemap: ${ORIGIN}/sitemap.xml`,
    '',
  ].join('\n');
}

const sitemapPath = path.join(ROOT, 'public', 'sitemap.xml');
const robotsPath = path.join(ROOT, 'public', 'robots.txt');
const xml = buildSitemap(PUBLIC_ROUTES);
writeFileSync(sitemapPath, xml, 'utf8');
writeFileSync(robotsPath, buildRobots(PUBLIC_ROUTES), 'utf8');

// A sitemap that got written but is malformed is worse than none — search engines
// drop the whole file. Cheap sanity check rather than a real XML parser: every
// route made it in, and the document is closed.
for (const route of PUBLIC_ROUTES) {
  if (!xml.includes(`<loc>${absoluteUrl(route.path)}</loc>`)) {
    throw new Error(`sitemap: route ${route.path} did not make it into the output`);
  }
}
if (!xml.trimEnd().endsWith('</urlset>')) throw new Error('sitemap: output is truncated');

console.log(
  `sitemap: wrote ${path.relative(ROOT, sitemapPath)} + ${path.relative(ROOT, robotsPath)} — ${PUBLIC_ROUTES.length} URL${PUBLIC_ROUTES.length === 1 ? '' : 's'} at ${ORIGIN}`,
);
