#!/usr/bin/env node
/**
 * The gate on src/lib/recommenders.js — roles, lead time, hours linkage,
 * emails, and per-program letter policy.
 *
 * There is no test runner in this repo, so this is the test suite for the one
 * module in the app whose output a student pastes into an email to a real
 * professional adult. What it protects:
 *
 *   1. THE LEAD-TIME BOUNDARIES. Twenty-nine days is short notice and thirty is
 *      not, and the whole nudge turns on that. Tested at exact days rather than
 *      approximately, with `now` injected — a test that ran "around today"
 *      would pass at every boundary by accident.
 *   2. THE SHORT-NOTICE EMAIL SAYS SO. A rushed ask that pretends the timing is
 *      normal is the version a busy clinician declines. Under a month, the
 *      generated draft must acknowledge it and offer an easy way out.
 *   3. NAME MATCHING NEVER OVER-MATCHES. Attaching one student's hours to the
 *      wrong Dr. Patel would put a fabricated claim in an email to a real
 *      person. "Patel" may match "Anjali Patel"; "Dr. A" must match nothing.
 *   4. THE SUMMARY IS BUILT FROM REAL ROWS ONLY. Every hour in the mentor
 *      summary must be traceable to a logged entry; an empty log must produce
 *      an honest "nothing found", never a plausible-looking blank.
 *   5. THE ONE SENTENCE THAT MUST STAY A BLANK. The personal specific — what
 *      the student actually took away — is deliberately left as a bracket. A
 *      letter request whose one human detail was generated by software is the
 *      exact thing this feature is against.
 *   6. "WE DON'T KNOW" IS A REAL ANSWER for letter policy. Telling a student a
 *      program does not use letters when we have not read its page means they
 *      do not ask, and they find out in October.
 *
 *   node scripts/verifyRecommenders.mjs
 */
import { register } from 'node:module';

register('./_appResolve.mjs', import.meta.url);

const R = await import('../src/lib/recommenders.js');
const { PROGRAMS } = await import('../src/data/combinedDegreePrograms.js');

let passed = 0;
const failures = [];
const assert = (label, cond, detail = '') => {
  if (cond) { passed += 1; return; }
  failures.push(`${label}${detail ? `\n      ${detail}` : ''}`);
};
const eq = (label, actual, expected) =>
  assert(label, actual === expected, `expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
const section = (n) => console.log(`\n${n}`);

// A fixed "today" so every boundary below is exact.
const TODAY = Date.parse('2026-08-22T09:00:00');
const inDays = (n) => new Date(TODAY + n * 86400000).toISOString().slice(0, 10);
const rec = (o = {}) => ({
  name: 'Dr. Anjali Patel',
  relationship: 'Physician or clinician you shadowed',
  type: 'individual',
  status: 'Planning to ask',
  ...o,
});

const SNAP = {
  clinicalHours: [
    { supervisor_name: 'Dr. Patel', hours: 8, entry_date: '2026-03-04', site_name: 'Mercy Hospital', site_type: 'Hospital', experience_kind: 'shadowing', notes: 'Full clinic day' },
    { supervisor_name: 'Anjali Patel', hours: 6, entry_date: '2026-05-11', site_name: 'Mercy Hospital', site_type: 'Hospital', experience_kind: 'shadowing' },
    { supervisor_name: 'R. Gomez', hours: 40, entry_date: '2026-01-10', site_name: 'Free Clinic', site_type: 'Community Health / Free Clinic', experience_kind: 'hands-on' },
  ],
  research: [{ mentor_name: 'Dr. Lin', title: 'Resistance survey', hours: 80, institution: 'State U' }],
  activities: [{ verifier_name: 'R. Gomez', position: 'Volunteer', organization: 'Free Clinic' }],
};

// ─────────────────────────────────────────────────────────────────────────────
section('1. The roles are the ones a health-pathway student actually has');

const REQUIRED_ROLES = ['shadowing-physician', 'research-mentor', 'volunteer-coordinator', 'clinical-supervisor'];
for (const id of REQUIRED_ROLES) {
  const role = R.ROLE_BY_ID[id];
  assert(`the ${id} role exists — the four the old teacher/counsellor/coach list missed`, !!role);
  if (!role) continue;
  assert(`${id} says what only that person can say`, String(role.whatTheyCanSay).length > 60);
  assert(`${id} says who counts`, String(role.whoCounts).length > 60);
  assert(`${id} names the notice it needs`, String(role.leadDaysAdvice).length > 20);
  assert(`${id} names the mistake students make with it`, String(role.commonMistake).length > 40);
}
assert('every role has a unique id', new Set(R.RECOMMENDER_ROLES.map(r => r.id)).size === R.RECOMMENDER_ROLES.length);
assert('every role label is offered in the picker', R.ROLE_LABELS.length === R.RECOMMENDER_ROLES.length);

// Rows written before these roles existed must not lose their evidence link.
eq('a legacy "Physician/Health Professional Shadowed" row maps to the shadowing role',
  R.roleFromRelationship('Physician/Health Professional Shadowed').id, 'shadowing-physician');
eq('a legacy "Research Mentor" row maps to the research role',
  R.roleFromRelationship('Research Mentor').id, 'research-mentor');
eq('an unrecognised relationship falls back to Other rather than throwing',
  R.roleFromRelationship('Neighbour who is a vet').id, 'other');

// ─────────────────────────────────────────────────────────────────────────────
section('2. Lead time, at the exact boundary');

eq('the minimum notice is one month', R.MIN_LEAD_DAYS, 30);

{
  const at29 = R.leadTimeStatus(rec({ due_date: inDays(29) }), TODAY);
  const at30 = R.leadTimeStatus(rec({ due_date: inDays(30) }), TODAY);
  eq('29 days out is urgent', at29.level, 'urgent');
  eq('29 days out is flagged as short notice', at29.shortNotice, true);
  assert('30 days out clears the minimum', at30.level !== 'urgent', `got ${at30.level}`);
  eq('30 days out is not short notice', at30.shortNotice, false);
  eq('30 days out is still called tight — a month is the floor, not the target', at30.level, 'tight');

  const at60 = R.leadTimeStatus(rec({ due_date: inDays(60) }), TODAY);
  eq('two months out is the position you want', at60.level, 'ok');

  const past = R.leadTimeStatus(rec({ due_date: inDays(-3) }), TODAY);
  eq('a passed deadline with no ask is overdue', past.level, 'overdue');
  eq('an overdue ask is short notice by definition', past.shortNotice, true);

  eq('no deadline set is unknown, not silently fine',
    R.leadTimeStatus(rec({}), TODAY).level, 'unknown');
}

// Follow-ups.
{
  const fresh = R.leadTimeStatus(rec({ status: 'Asked', asked_at: inDays(-3), due_date: inDays(60) }), TODAY);
  const stale = R.leadTimeStatus(rec({ status: 'Asked', asked_at: inDays(-12), due_date: inDays(60) }), TODAY);
  eq('three days after asking, nothing is due', fresh.needsFollowUp, false);
  eq('twelve days after asking, a follow-up is due', stale.needsFollowUp, true);
  assert('the follow-up message says following up is normal', /normal/i.test(stale.message));

  // Status "Asked" with no date is a real state and must not be read as "asked today".
  const undated = R.leadTimeStatus(rec({ status: 'Asked', due_date: inDays(60) }), TODAY);
  eq('an asked row with no date does not invent one', undated.daysSinceAsked, null);
  assert('it asks for the date instead', /when/i.test(undated.message));

  eq('a submitted letter is done', R.leadTimeStatus(rec({ status: 'Submitted' }), TODAY).level, 'done');
  assert('a submitted letter prompts a thank-you', /thank/i.test(R.leadTimeStatus(rec({ status: 'Submitted' }), TODAY).message));
}

// The nudge strip: worst first, and calm rows excluded.
{
  const rows = [
    rec({ id: 'a', due_date: inDays(90) }),                                  // ok
    rec({ id: 'b', due_date: inDays(10) }),                                  // urgent
    rec({ id: 'c', due_date: inDays(-5) }),                                  // overdue
    rec({ id: 'd', due_date: inDays(40) }),                                  // tight
    rec({ id: 'e', status: 'Submitted' }),                                   // done
  ];
  const out = R.needsAttention(rows, TODAY);
  eq('only the rows that need something appear', out.length, 3);
  eq('the overdue one is first', out[0].entry.id, 'c');
  eq('the urgent one is second', out[1].entry.id, 'b');
  assert('the comfortable and finished rows are left alone',
    !out.some(x => ['a', 'e'].includes(x.entry.id)));
}

// ─────────────────────────────────────────────────────────────────────────────
section('3. Name matching is conservative in the direction that matters');

assert('an exact name matches', R.samePerson('Anjali Patel', 'anjali patel'));
assert('a title is ignored', R.samePerson('Dr. Patel', 'Patel'));
assert('a surname matches a full name', R.samePerson('Patel', 'Anjali Patel'));
assert('a different surname does not match', !R.samePerson('Smith', 'Anjali Patel'));
assert('an initial alone never matches — this is the one that would fabricate a claim',
  !R.samePerson('Dr. A', 'Anjali Patel'));
assert('an empty name matches nothing', !R.samePerson('', 'Anjali Patel'));
assert('two different people with a shared first name do not match',
  !R.samePerson('Anjali Shah', 'Anjali Patel'));

// ─────────────────────────────────────────────────────────────────────────────
section('4. The hours linkage');

{
  const link = R.hoursForRecommender(rec({}), SNAP);
  eq('both spellings of the same supervisor are found', link.visits, 2);
  eq('their hours are summed', link.clinicalHours, 14);
  eq('the shadowing split is preserved', link.shadowingHours, 14);
  eq('someone else\'s hours are not attached', link.entries.some(e => e.supervisor_name === 'R. Gomez'), false);
  eq('the site is captured', link.sites.join(), 'Mercy Hospital');
  eq('the date range starts at the first visit', link.firstDate, '2026-03-04');
  eq('and ends at the last', link.lastDate, '2026-05-11');

  const mentor = R.hoursForRecommender(rec({ name: 'Dr. Lin' }), SNAP);
  eq('a research mentor is matched through research rows', mentor.research.length, 1);
  eq('their research hours count toward the total', mentor.totalHours, 80);

  const coordinator = R.hoursForRecommender(rec({ name: 'R. Gomez' }), SNAP);
  eq('a volunteer coordinator is matched through clinical hours', coordinator.clinicalHours, 40);
  eq('and through the activities they verified', coordinator.activities.length, 1);

  const unknown = R.hoursForRecommender(rec({ name: 'Dr. Nobody' }), SNAP);
  eq('an unmatched name finds nothing rather than guessing', unknown.totalHours, 0);
  eq('and still returns a usable shape', Array.isArray(unknown.entries), true);
}

// ─────────────────────────────────────────────────────────────────────────────
section('5. The mentor summary contains only logged facts');

{
  const summary = R.buildMentorSummary(rec({}), SNAP, { studentName: 'Maya Chen' });
  assert('it names the student', summary.includes('Maya Chen'));
  assert('it states the hours total', summary.includes('14 hours'));
  assert('it states the number of visits', /2 visits/.test(summary));
  assert('it lists each session with its own date', summary.includes('March 4, 2026') && summary.includes('May 11, 2026'));
  assert('it carries the note from the log', summary.includes('Full clinic day'));
  assert('it says the log was kept as it happened', /as it happened/i.test(summary));
  assert('it does not claim hours with anyone else', !summary.includes('Free Clinic'));

  const empty = R.buildMentorSummary(rec({ name: 'Dr. Nobody' }), SNAP, { studentName: 'Maya Chen' });
  assert('an empty match says so plainly', /could not find/i.test(empty));
  assert('and tells the student how to fix it', /spell|match/i.test(empty));
}

// ─────────────────────────────────────────────────────────────────────────────
section('6. The emails');

{
  const normal = R.emailTemplates(rec({ due_date: inDays(60) }), SNAP, { studentName: 'Maya Chen', todayMs: TODAY });
  const rushed = R.emailTemplates(rec({ due_date: inDays(12) }), SNAP, { studentName: 'Maya Chen', todayMs: TODAY });

  eq('four emails are offered', normal.length, 4);
  assert('every one has a subject and a body',
    normal.every(t => String(t.subject).length > 5 && String(t.body).length > 100));
  assert('every one explains when to send it', normal.every(t => String(t.note).length > 40));

  const ask = normal.find(t => t.id === 'ask');
  assert('the ask is addressed to them by name', ask.body.startsWith('Dear Dr. Anjali Patel'));
  assert('the ask carries the real logged hours', ask.body.includes('14 hours'));
  assert('the ask names the real site', ask.body.includes('Mercy Hospital'));
  assert('the ask is signed by the student', ask.body.includes('Maya Chen'));
  assert('the ask leaves the personal specific as a blank — the one thing software must not write',
    /\[One or two sentences/.test(ask.body));
  assert('a comfortable deadline does not apologise for the timing', !/short notice/i.test(ask.body));

  const rushedAsk = rushed.find(t => t.id === 'ask');
  assert('a short-notice ask says so up front', /short notice/i.test(rushedAsk.body));
  assert('and offers an easy way to decline', /say no|not possible/i.test(rushedAsk.body));
  assert('and the tab is labelled as the short-notice version', /short notice/i.test(rushedAsk.label));

  const summary = normal.find(t => t.id === 'summary');
  assert('the summary email embeds the hours summary', summary.body.includes('WHAT WE DID TOGETHER'));

  const followUp = normal.find(t => t.id === 'follow-up');
  assert('the follow-up gives them permission to say no', /no hard feelings/i.test(followUp.body));

  // Nothing may be sent with an unresolved template artefact in it.
  for (const t of normal) {
    assert(`${t.id}: no undefined leaked into the draft`, !/undefined|null|NaN/.test(t.body), t.body.slice(0, 160));
  }

  // A student with no logged hours must still get a sendable email.
  const bare = R.emailTemplates(rec({ name: 'Mr. Ruiz', relationship: 'Teacher', due_date: inDays(60) }),
    { clinicalHours: [], research: [], activities: [] }, { studentName: 'Maya Chen', todayMs: TODAY });
  assert('a teacher with no hours still gets a complete ask', bare[0].body.length > 300);
  assert('and it does not claim hours that do not exist', !/\d+ hours across/.test(bare[0].body));
}

// ─────────────────────────────────────────────────────────────────────────────
section('7. Whether a program uses letters at all');

{
  const psu = PROGRAMS.find(p => p.id === 'psu-jefferson-pmm');
  assert('the catalog still carries the program that does NOT use letters', !!psu);
  const policy = R.lettersPolicyFor(psu);
  eq('it is reported as not using letters', policy.used, false);
  eq('on an official basis', policy.basis, 'official');
  assert('and says what to do instead', policy.note.length > 40);

  const unread = R.lettersPolicyFor({ id: 'x', recommendations: undefined });
  eq('a program we have not read returns "we do not know", never "not required"', unread.used, null);
  assert('and tells the student to assume letters are wanted',
    /assume/i.test(unread.note),
    'the expensive error here is a student not asking because we guessed');

  const usesThem = R.lettersPolicyFor({ id: 'y', recommendations: { used: true, basis: 'official', note: 'Two letters.' } });
  eq('a program that says it uses letters is reported as such', usesThem.used, true);

  const summary = R.lettersPolicySummary(PROGRAMS);
  eq('every catalog program is classified', summary.rows.length, PROGRAMS.length);
  eq('the three buckets partition the catalog',
    summary.used.length + summary.notUsed.length + summary.unknown.length, PROGRAMS.length);
  assert('at least one program is known not to use letters', summary.notUsed.length >= 1);
  assert('at least one is known to use them', summary.used.length >= 1);
}

// ─────────────────────────────────────────────────────────────────────────────
console.log('');
if (failures.length) {
  console.error(`✗ ${failures.length} failed, ${passed} passed\n`);
  failures.forEach(f => console.error(`  • ${f}`));
  process.exit(1);
}
console.log(`✓ Recommenders verified — ${passed} assertions.`);
console.log(`  ${R.RECOMMENDER_ROLES.length} roles, 4 email templates, ${R.MIN_LEAD_DAYS}-day minimum lead time.`);
